# Project information
site_name: FUXI.IS
site_url: https://zhangyouyi125.github.io/wiki/
site_description: FUXI.IS
site_author: FUXI.IS

# Repository
repo_name: FUXI.IS
repo_url: https://github.com/zhangyouyi125/wiki
edit_uri: https://github.com/zhangyouyi125/wiki

# Copyright
copyright: "©2021 FUXI institution. All Rights Reserved.  联系方式:support@fuxiinstitution.org"

theme:
  name: material
  custom_dir: material
  # icon:
  #   logo: ./assets/8.png
  logo: ./assets/images/logo.png
    #icon: image/8.png
  highlightjs: true        # 打开代码高亮
  hljs_style: github       # 代码高亮风格
  hljs_languages:          # 编程语言
    - c
    - c++
    - java
    - python
    - go
    - yaml
  features:
    - content.code.annotate
    - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    # - search.suggest
    # - toc.integrate

  palette:
    - scheme: default
      primary: white
      accent: pink
      # toggle:
      #   icon: material/toggle-switch
      #   name: Switch to dark mode
    # - scheme: slate
    #   primary: black
    #   accent: red
    #   toggle:
    #     icon: material/toggle-switch-off-outline
    #     name: Switch to light mode
    
  

nav:
  - 主页: index.md
  - 产品白皮书: WhitePaper/WhitePaper.md
  # 下面代表的是一组页面
  - API 接口: 
    - 接口文档: API_Guide/API_Guide.md
    - 接口试用: API_Guide/API_Usage.md
  - 开发者: Developer/Developer.md
  - 合作伙伴: Cooperator/Cooperator.md
  - 关于我们: AboutUs/AboutUs.md

extra_css:
  - stylesheets/extra.css

extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/FuxiInstitution
    - icon: fontawesome/brands/weibo
      link: https://weibo.com/u/7206532842
    - icon: fontawesome/brands/weixin
      link: https://mp.weixin.qq.com/s/0nhfsh22n0kEOzupWEZX2Q
    - icon: fontawesome/brands/github
      link: https://twitter.com/squidfunk
  

    

  disqus: 'fuxiis'
   

plugins:
  - search



markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
  - attr_list
  - md_in_html


  

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

